baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "FalOn's Blog"

theme = 'github-style'


[params]
  author = "Falon"
  github = "falOn-Dev"
  description = "In this world, it's either cook or get cooked chump."
  email = "falon@team2537.com"
  location = "The Shop"
  headerIcon = "https://raw.githubusercontent.com/primer/octicons/345a8f5915b6ec4ff6cca3eb1ae76cb4744ba2de/icons/cpu-24.svg"